# Generated by Django 5.2.7 on 2025-10-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('release_year', models.IntegerField(verbose_name='公開年')),
                ('director', models.CharField(max_length=100, verbose_name='監督名')),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='ポスターURL')),
            ],
        ),
        migrations.CreateModel(
            name='CriticReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critic_name', models.CharField(max_length=100, verbose_name='批評家名')),
                ('is_hot', models.BooleanField(verbose_name='評価（ホット/コールド）')),
                ('source_url', models.URLField(max_length=500, verbose_name='元記事URL')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie', verbose_name='対象映画')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='星評価')),
                ('comment', models.TextField(verbose_name='レビュー本文')),
                ('username', models.CharField(max_length=50, verbose_name='ユーザー名')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie', verbose_name='対象映画')),
            ],
        ),
    ]
