# Generated by Django 5.2.7 on 2025-10-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticreview',
            name='critic_name',
            field=models.CharField(max_length=100, verbose_name='レビュー担当者'),
        ),
    ]
