# Generated by Django 5.2.7 on 2025-10-13 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_criticreview_critic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
            ],
            options={
                'verbose_name': '人物 (監督・キャストなど)',
                'verbose_name_plural': '人物 (監督・キャストなど)',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='main_cast',
            field=models.ManyToManyField(related_name='acted_in_movies', to='reviews.person', verbose_name='メインキャスト'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_movies', to='reviews.person', verbose_name='監督'),
        ),
    ]
