# Generated by Django 5.2.7 on 2025-10-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_person_movie_main_cast_alter_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticreview',
            name='critic_name',
        ),
        migrations.AddField(
            model_name='criticreview',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='レビュー本文'),
        ),
        migrations.AddField(
            model_name='criticreview',
            name='is_critic',
            field=models.BooleanField(default=False, verbose_name='批評家レビュー'),
        ),
        migrations.AddField(
            model_name='criticreview',
            name='reviewer_name',
            field=models.CharField(default='既存の批評家', max_length=100, verbose_name='投稿者名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='元記事URL'),
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
