# Generated by Django 5.2.7 on 2025-10-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_criticreview_critic_name_criticreview_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ホーム画面で特集表示'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TMDb ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='予告編URL（YouTube）'),
        ),
    ]
