# Generated by Django 5.2.7 on 2025-10-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='column_images/', verbose_name='サムネイル画像'),
        ),
    ]
