# Generated by Django 5.2.7 on 2025-11-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_userprofile_notify_on_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='post_type',
            field=models.CharField(choices=[('official', '編集部記事'), ('community', 'みんなの声')], default='community', max_length=20, verbose_name='投稿種別'),
        ),
        migrations.AddField(
            model_name='comment',
            name='old_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.criticreview', verbose_name='旧レビュー'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_released',
            field=models.BooleanField(default=True, verbose_name='公開済み'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='公開日'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_movie_buff',
            field=models.BooleanField(default=False, verbose_name='映画通ユーザー'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectation', models.IntegerField(blank=True, null=True, verbose_name='期待度（0-100）')),
                ('satisfaction', models.IntegerField(blank=True, null=True, verbose_name='満足度（0-100）')),
                ('is_movie_buff', models.BooleanField(default=False, verbose_name='映画通ユーザー')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie', verbose_name='対象映画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'レビュー',
                'verbose_name_plural': 'レビュー',
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review', verbose_name='レビュー'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='レビュー'),
        ),
    ]
