# Generated by Django 5.2.7 on 2025-11-11 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_column_post_type_comment_old_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_on_column', 'コラムへのコメント'), ('like_on_column', 'コラムへのいいね'), ('comment_on_review', 'レビューへのコメント'), ('follow', '新しいフォロワー')], max_length=30, verbose_name='通知タイプ'),
        ),
        migrations.CreateModel(
            name='MovieRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='推薦スコア')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie', verbose_name='おすすめ映画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'おすすめ映画',
                'verbose_name_plural': 'おすすめ映画',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('spam', 'スパム'), ('inappropriate', '不適切なコンテンツ'), ('harassment', 'ハラスメント'), ('copyright', '著作権侵害'), ('other', 'その他')], max_length=20, verbose_name='報告理由')),
                ('content_type', models.CharField(choices=[('review', 'レビュー'), ('column', 'コラム'), ('comment', 'コメント')], max_length=10, verbose_name='報告対象')),
                ('description', models.TextField(max_length=500, verbose_name='詳細')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='解決済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='報告日時')),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.column', verbose_name='コラム')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.comment', verbose_name='コメント')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='レビュー')),
            ],
            options={
                'verbose_name': '報告',
                'verbose_name_plural': '報告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='フォロー日時')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='フォローする人')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='フォローされる人')),
            ],
            options={
                'verbose_name': 'フォロー',
                'verbose_name_plural': 'フォロー',
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='いいね日時')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.review', verbose_name='レビュー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'レビューいいね',
                'verbose_name_plural': 'レビューいいね',
                'unique_together': {('user', 'review')},
            },
        ),
    ]
