# Generated by Django 5.2.7 on 2025-11-12 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_alter_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticreview',
            options={'ordering': ['-created_at'], 'verbose_name': '批評家レビュー', 'verbose_name_plural': '批評家レビュー'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'お気に入り', 'verbose_name_plural': 'お気に入り'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at'], 'verbose_name': 'フォロー', 'verbose_name_plural': 'フォロー'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-popularity', '-release_date'], 'verbose_name': '映画', 'verbose_name_plural': '映画'},
        ),
        migrations.AlterModelOptions(
            name='movierecommendation',
            options={'ordering': ['-score', '-created_at'], 'verbose_name': 'おすすめ映画', 'verbose_name_plural': 'おすすめ映画'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '人物', 'verbose_name_plural': '人物'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'レビュー', 'verbose_name_plural': 'レビュー'},
        ),
        migrations.AlterModelOptions(
            name='reviewlike',
            options={'ordering': ['-created_at'], 'verbose_name': 'レビューいいね', 'verbose_name_plural': 'レビューいいね'},
        ),
        migrations.RemoveField(
            model_name='column',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='column',
            name='related_movies',
        ),
        migrations.RemoveField(
            model_name='column',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='old_review',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='criticreview',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='criticreview',
            name='is_critic',
        ),
        migrations.RemoveField(
            model_name='criticreview',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='criticreview',
            name='reviewer_name',
        ),
        migrations.RemoveField(
            model_name='criticreview',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_released',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='main_cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='report',
            name='column',
        ),
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_movie_buff',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', verbose_name='コメント内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criticreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投稿日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criticreview',
            name='critic_name',
            field=models.CharField(default='不明', max_length=100, verbose_name='批評家名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criticreview',
            name='publication',
            field=models.CharField(default='不明', max_length=100, verbose_name='掲載媒体'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criticreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='評価'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criticreview',
            name='review_text',
            field=models.TextField(default='レビューなし', verbose_name='レビュー本文'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='背景画像パス'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movies_acted_in', to='reviews.person', verbose_name='キャスト'),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='原題'),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, verbose_name='あらすじ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=0, verbose_name='人気度'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='ポスター画像パス'),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='上映時間（分）'),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0, verbose_name='平均評価'),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='評価数'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='通知', verbose_name='通知内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='object_id',
            field=models.IntegerField(default=0, verbose_name='オブジェクトID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'スパム'), ('harassment', 'ハラスメント'), ('inappropriate', '不適切な内容'), ('copyright', '著作権侵害'), ('other', 'その他')], default='other', max_length=20, verbose_name='理由'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default='レビューなし', verbose_name='レビュー本文'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='column',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='column',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='column_images/', verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critic_reviews', to='reviews.movie', verbose_name='映画'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='追加日時'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='reviews.person', verbose_name='監督'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='TMDb ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='予告編URL'),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie', verbose_name='映画'),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='reason',
            field=models.TextField(blank=True, verbose_name='理由'),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='score',
            field=models.FloatField(verbose_name='おすすめスコア'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'コメント'), ('like', 'いいね'), ('follow', 'フォロー')], max_length=20, verbose_name='通知タイプ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('review', 'レビュー'), ('column', 'コラム'), ('comment', 'コメント')], max_length=20, verbose_name='コンテンツタイプ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='review',
            name='expectation',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='期待度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie', verbose_name='映画'),
        ),
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='満足度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='アバター'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='自己紹介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_movie_buff',
            field=models.BooleanField(default=False, verbose_name='映画通バッジ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_on_comment',
            field=models.BooleanField(default=True, verbose_name='コメント通知'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_on_like',
            field=models.BooleanField(default=True, verbose_name='いいね通知'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='追加日時'),
        ),
        migrations.AlterField(
            model_name='watchstatus',
            name='status',
            field=models.CharField(choices=[('want_to_watch', '観たい'), ('watched', '観た')], default='want_to_watch', max_length=20, verbose_name='ステータス'),
        ),
    ]
