# Generated by Django 5.2.7 on 2025-11-13 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0016_alter_criticreview_options_alter_favorite_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticreview',
            options={'ordering': ['-created_at'], 'verbose_name': '評論家レビュー', 'verbose_name_plural': '評論家レビュー'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'お気に入り', 'verbose_name_plural': 'お気に入り'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'フォロー', 'verbose_name_plural': 'フォロー'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-popularity'], 'verbose_name': '映画', 'verbose_name_plural': '映画'},
        ),
        migrations.AlterModelOptions(
            name='movierecommendation',
            options={'ordering': ['-score'], 'verbose_name': '映画レコメンド', 'verbose_name_plural': '映画レコメンド'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': '通報', 'verbose_name_plural': '通報'},
        ),
        migrations.AlterModelOptions(
            name='reviewlike',
            options={'verbose_name': 'レビューいいね', 'verbose_name_plural': 'レビューいいね'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('movie', 'user')},
        ),
        migrations.RemoveField(
            model_name='movierecommendation',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='column',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='review',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='リンク'),
        ),
        migrations.AlterField(
            model_name='column',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='column_thumbnails/', verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='critic_name',
            field=models.CharField(max_length=100, verbose_name='評論家名'),
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie', verbose_name='映画'),
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='publication',
            field=models.CharField(blank=True, max_length=100, verbose_name='掲載メディア'),
        ),
        migrations.AlterField(
            model_name='criticreview',
            name='rating',
            field=models.IntegerField(verbose_name='評価（0-100）'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='acted_movies', to='reviews.person', verbose_name='キャスト'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDb ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default='', verbose_name='予告編URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0, verbose_name='TMDb評価'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='TMDb投票数'),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='score',
            field=models.FloatField(verbose_name='レコメンドスコア'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'コメント'), ('like', 'いいね'), ('follow', 'フォロー'), ('review_like', 'レビューいいね')], max_length=20, verbose_name='通知タイプ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='送信者'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='コンテンツタイプ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='通報日時'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='オブジェクトID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'スパム'), ('harassment', 'ハラスメント'), ('inappropriate', '不適切な内容'), ('other', 'その他')], max_length=20, verbose_name='理由'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='通報者'),
        ),
        migrations.AlterField(
            model_name='review',
            name='expectation',
            field=models.IntegerField(default=50, verbose_name='期待値メーター（0-100）'),
        ),
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.IntegerField(blank=True, null=True, verbose_name='満足度スコア（0-100）'),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_movie_buff',
            field=models.BooleanField(default=False, verbose_name='映画通ユーザー'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='watchstatus',
            name='status',
            field=models.CharField(choices=[('watched', '見た'), ('watching', '見てる'), ('want_to_watch', '見たい')], max_length=20, verbose_name='ステータス'),
        ),
    ]
