# Generated by Django 5.2.7 on 2025-11-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_notification_column_notification_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='YouTube動画ID'),
        ),
    ]
