# Generated by Django 5.2.7 on 2025-11-15 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_movie_trailer_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FanArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fanarts/', verbose_name='アート画像')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanarts', to='reviews.movie', verbose_name='関連映画')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'ファンアート',
                'verbose_name_plural': 'ファンアート',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FanArtLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('fanart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.fanart', verbose_name='ファンアート')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ファンアートいいね',
                'verbose_name_plural': 'ファンアートいいね',
                'unique_together': {('user', 'fanart')},
            },
        ),
    ]
