# Generated by Django 5.2.7 on 2025-11-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_fanart_fanartlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_now_playing_jp',
            field=models.BooleanField(default=False, verbose_name='日本で現在公開中'),
        ),
        migrations.AddField(
            model_name='movie',
            name='jp_release_date',
            field=models.DateField(blank=True, null=True, verbose_name='日本公開日'),
        ),
    ]
